### ISSUE TITLE
 Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Landroid_serialport_api/SerialPort

### ISSUE THREAD

**Issue by fabiomig** [Neuralink/serialprinterplugin#1]
Hi, I'm trying to use your plugin in my project but its giving me this error while opening the apk

W/dalvikvm(24207): Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Landroid_serialport_api/SerialPort;
W/System.err(24207): java.lang.ExceptionInInitializerError
W/System.err(24207):    at com.hdx.lib.serial.SerialPortOperaion.StartSerial(SerialPortOperaion.java:52)
W/System.err(24207):    at com.hdx.lib.printer.SerialPrinter.OpenPrinter(SerialPrinter.java:38)
W/System.err(24207):    at com.neuralink.cordova.serialprinterplugin.SerialPrinterPlugin.execute(SerialPrinterPlugin.java:58)
W/System.err(24207):    at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:95)
W/System.err(24207):    at org.apache.cordova.PluginManager.exec(PluginManager.java:130)
W/System.err(24207):    at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
W/System.err(24207):    at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
W/System.err(24207):    at android.webkit.JWebCoreJavaBridge.sharedTimerFired(Native Method)
W/System.err(24207):    at android.webkit.JWebCoreJavaBridge.sharedTimerFired(Native Method)
W/System.err(24207):    at android.webkit.JWebCoreJavaBridge.fireSharedTimer(JWebCoreJavaBridge.java:92)
W/System.err(24207):    at android.webkit.JWebCoreJavaBridge.handleMessage(JWebCoreJavaBridge.java:108)
W/System.err(24207):    at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(24207):    at android.os.Looper.loop(Looper.java:137)
W/System.err(24207):    at android.webkit.WebViewCore$WebCoreThread.run(WebViewCore.java:812)
W/System.err(24207):    at java.lang.Thread.run(Thread.java:856)
W/System.err(24207): Caused by: java.lang.UnsatisfiedLinkError: Couldn't load serial_port from loader dalvik.system.PathClassLoader[dexPath=/data/app/io.cordova.hellocordova-2.apk,libraryPath=/data/app-lib/io.cordova.hellocordova-2]: findLibrary returned null
W/System.err(24207):    at java.lang.Runtime.loadLibrary(Runtime.java:365)
W/System.err(24207):    at java.lang.System.loadLibrary(System.java:535)
W/System.err(24207):    at android_serialport_api.SerialPort.<clinit>(SerialPort.java:69)

**Comment by victorsosa** [comment]
I know this is old but may help someone.

Maybe missing this line of code to init the native library

```
    static {
        System.loadLibrary("android_serialport_api");
    }
```

**Comment by ksmartkb** [comment]
think you for you response.... i have failed to load it have tried
many times hence almost given up... might your have the source code
for the same serialprinter. your response will be appreciated
